replicaCount: 1

image:
  repository: porrametp/demo-application
  pullPolicy: IfNotPresent
  tag: main
  secretName: ibmcr-pull-image

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9090

ingress:
  enabled: true
  annotations: {}
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 1000Mi
  requests:
    cpu: 50m
    memory: 400Mi