replicaCount:
  minCount: 2
  maxCount: 4
image:
  repository: porrametp/demo-application
  pullPolicy: IfNotPresent
  tag: sha-241bf92
  secretName: ibmcr-pull-image
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
service:
  type: ClusterIP
  port: 9090
ingress:
  enabled: true
  annotations: {}
  tls: []
resources:
  limits:
    cpu: 100m
    memory: 1000Mi
  requests:
    cpu: 50m
    memory: 400Mi
hpa:
  values: 1
  policiesType: Pods
  stabilizationUp: 30
  stabilizationDown: 900
  name: cpu
  type: Utilization
  average: 55
