apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "demo-python-app.fullname" . }}
  labels:
    app: {{ template "demo-python-app.name" . }}
    chart: {{ template "demo-python-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "demo-python-app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "demo-python-app.name" . }}
        release: {{ .Release.Name }}
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      imagePullSecrets:
        - name: {{ .Values.image.secretName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_NAME
              value: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          livenessProbe:
            httpGet:
              path: /livez
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 20